### ISSUE TITLE
Permission denied error for creating renate-sample directory

### ISSUE THREAD

**Issue by suhaibasaeed** [bachng2017/RENAT#27]
I am trying to run RENAT following the guide using a container. I am running into the below error in step 4 where I get permission denied errors. I do not know the sudo password for this container so I obviously cannot use that.

`bash-4.2$ whoami   
robot  
bash-4.2$ pwd  
/home/robot/work/renat  
bash-4.2$ $RENAT_PATH/tools/project.sh renate-sample
mkdir: cannot create directory ‘renate-sample’: Permission denied
cp: target ‘renate-sample’ is not a directory
find: ‘renate-sample’: No such file or directory
created test project:  renate-sample
use item.sh to create test case
`

Is there a workaround for this issue?

**Comment by starrsl** [comment]
Seems the robot user on the image does not have permissions to the configured default folder.

Switching to the robot users home dir seems to fix the issue.
