### ISSUE TITLE
VChannel - Key Error - No local.yaml

### ISSUE THREAD

**Issue by starrsl** [bachng2017/RENAT#6]
[https://github.com/bachng2017/RENAT/blob/master/VChannel.py#L305](url)

The following code snippet makes no allowences for running VChannel in the absence of a local.yaml file.

As the code only warns if local.yaml is missing i can only assume it is intended that it is possible to test in its absence without it defaulting to the global devices information/manually specified connect statements.

Suggested fix open within a PR

[https://github.com/bachng2017/RENAT/pull/7](url)

**Comment by bachng2017** [comment]
fixed by PR https://github.com/bachng2017/RENAT/pull/7. Thanks

**Comment by bachng2017** [comment]
I messed with the git history, fixed it. Please make a new PR and sorry for your inconvenience

**Comment by bachng2017** [comment]
fixed by PR https://github.com/bachng2017/RENAT/pull/9
